config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only:[:show, :index, :edit, :create, :destroy]
  resources :users, only:[:show, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

 	def after_sign_in_path_for(resource)
 		user_path(current_user.id)
 	end
 	def after_sign_out_path_for(resource)
 		root_path
 	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def create
  	book = Book.new(book_params)
  	book.save
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redierect_to user_path(current_user.id)
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@book = Book.new
    @books = Book.all
  	@user = User.find(params[:id])

  end

  def index
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	user.update(user_params)
  	redirect_to user_path(user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
	<%= form_for(book) do |f| %>
	<h5>Title</h5>
	<%= f.text_field :title %>
	<h5>Opinion</h5>
	<%= f.text_area :body %>
	<button class="btn btn-primary " type="submit">Create Book</button>
	<% end %>

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body　%>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>

app/views/homes/about.html.erb
<div class ="container">
	
	<h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
</div>

app/views/homes/top.html.erb
<div class ="container">
	<div class ="row">
		<div class="col-md-6 offset-md-3 col-xs-8 offset-xs-2">
			<h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
			<p>In Bookers,<br>
			you can share and exchange your opinions , inpressions , and emotions<br>
			about various books!</p>

			<%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-block" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-block" %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/188b0a3462.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class ="container">
          <h4 class="navbar-brand">Bookers</h4>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <a class="nav-link" href="#"><i class="fas fa-home"></i>Home </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><i class="fas fa-user"></i>Users </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><i class="fas fa-book"></i>Books </a>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path,class:"nav-link",method: :delete do%>
                    <i class="fas fa-sign-out-alt">logout</i>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path,class:"nav-link" do%>
                    <i class="fas fa-home">Home</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path ,class:"nav-link" do%>
                    <i class="fas fa-link">About</i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path ,class:"nav-link" do %><i class="fas fa-user-plus">sign up </i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path ,class:"nav-link" do%>
                    <i class="fas fa-sign-in-alt">login</i>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_profile.html.erb
<table class="table">
	<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th><%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
			<i class="fas fa-wrench"></i>
		<% end %>
		</th>
	</tr>
</table>

app/views/users/edit.html.erb
<div class ="container">
	<%= form_for(@user) do |f| %>
		<h4>Name</h4>
		<%= f.text_field :name %>
		<h4>Introduction</h4>
		<%= f.text_area :introduction %>
		<%= f.attachment_field :profile_image%>
		<%= f.submit %>
	<% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class ="container">
	<div class ="row">
		<div class ="col-xs-3 col-md-3">
			<h2>User</h2>
			<%= render 'users/profile', user: @user %>
			<h2>NEW BOOK</h2>
			<%= render 'books/form', book: @book %>
		</div>
		<div class ="col-xs-9 col-md-9">
			
			<table class ="table table-hover">
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th></th>
				<% @books.each do |book| %>
				<tr>
					<td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size: "50x50") %>
					</td>
					<td><%= book.title %></td>
					<td><%= book.body %></td>

				</tr>
				<% end %>
			</table>
			
		</div>

	</div>
</div>